name: PR Pipeline

on: [ pull_request, workflow_dispatch ]


jobs:

  install_dev:
    name: Install Dev Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Install Dependencies
        run: make dev -B

  # ------------------------------------------------------------------------------------------------------------------------

  syntax_checks:
    name: Syntax Checks
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
        # -----------------------------------
      - name: PHP Syntax Checks
        run: make phpcheck -B

  php_min:
    name: PHP Minimum Compatibility
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: PHP Minimum Checks
        run: make phpmin -B

  unit_tests:
    name: Unit Tests
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Run PHPUnit
        run: make phpunit -B

  infection:
    name: Mutation Tests
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Run Tests
        run: make infection -B

  phpstan:
    name: PHPStan Analyzer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Run PHPStan
        run: make stan -B

  phpcsfixer:
    name: PHP CS Fixer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Run PHP CS Fixer
        run: make csfix -B

  phpmnd:
    name: PHP Magic Numbers Analyzer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Run Test
        run: make phpmnd -B

  rector:
    name: Rector Analyzer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Run Rector
        run: make rector -B

  # ------------------------------------------------------------------------------------------------------------------------

  svrunit:
    name: SVRUnit Tests
    needs: [ syntax_checks, php_min, unit_tests, phpstan, phpcsfixer ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          ini-values: phar.readonly=OFF
        # -----------------------------------
      - name: Build PHAR
        run: make build -B
        # -----------------------------------
      - name: Install SVRUnit
        run: make dev -B
        # -----------------------------------
      - name: Start SVRUnit
        run: make svrunit -B