name: Step Review

on:
  workflow_call:
    inputs:
      PHP_VERSION:
        description: "PHP Version"
        required: true
        type: string


jobs:

  # ------------------------------------------------------------------------------------------------------------------------

  install_dev:
    name: Install Dev Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v4
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Install Dependencies
        run: make dev -B

  # ------------------------------------------------------------------------------------------------------------------------

  syntax_checks:
    name: Syntax Checks
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
        # -----------------------------------
      - name: PHP Syntax Checks
        run: make phpcheck -B

  php_min:
    name: PHP Minimum Compatibility
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v4
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: PHP Minimum Checks
        run: make phpmin -B

  unit_tests:
    name: Unit Tests
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v4
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Run PHPUnit
        run: make phpunit -B

  infection:
    name: Mutation Tests
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v4
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Run Tests
        run: make infection -B

  phpstan:
    name: PHPStan Analyzer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v4
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Run PHPStan
        run: make stan -B

  phpcsfixer:
    name: PHP CS Fixer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v4
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Run PHP CS Fixer
        run: make csfix -B

  phpmnd:
    name: PHP Magic Numbers Analyzer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v4
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Run Test
        run: make phpmnd -B

  rector:
    name: Rector Analyzer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v4
        with:
          key: cache-dev-${{ github.run_id }}
          path: |
            vendor
        # -----------------------------------
      - name: Run Rector
        run: make rector -B

  # ------------------------------------------------------------------------------------------------------------------------

  svrunit:
    name: SVRUnit Tests
    needs: [ syntax_checks, php_min, unit_tests, phpstan, phpcsfixer ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
          ini-values: phar.readonly=OFF
      - name: Install aspell
        run: sudo apt-get update && sudo apt-get install -y aspell aspell-en
        # -----------------------------------
      - name: Build PHAR
        run: make prod && make build -B
        # -----------------------------------
      - name: Build Docker Image
        run: make docker version=dev-main
        # -----------------------------------
      - name: Install SVRUnit
        run: make dev -B
        # -----------------------------------
      - name: Start SVRUnit
        run: make svrunit -B
        # -----------------------------------
      - name: Store SVRUnit Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: svrunit_report
          retention-days: 3
          path: |
            ${{ github.workspace }}/.reports
        # -----------------------------------
      - name: Build JUnit Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: SVRUnit Report
          path: .reports/report.xml
          reporter: jest-junit
